### PR TITLE
Support for float ranges

### PR DESCRIPTION
**Pull request by danchoi**
Tested with this separate repo: https://github.com/danchoi/sphinx-test

### CODE REVIEW

**Comment by gregwebs** [comment]
oh, here is the pull request :) Is it possible to include your example test code in the pull request?

**Comment by danchoi** [comment]
Sorry, which part of the ad hoc test code are you referring to and where exactly should it go?

**Comment by danchoi** [comment]
Done

**Comment by gregwebs** [comment]
Thanks! This is a non-breaking change, so I will release it with a small version bump.

**Comment by danchoi** [comment]
Thank you.

**Pull request merged**
